{{ if eq .Values.fixicc_agent.storage.class "storage-fixicc-agent" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-fixicc-agent
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: gp2
  encrypted: 'true'
reclaimPolicy: Delete
{{ end }}